name: benchmark (labeled)

on: # TODO: delete this file when specifying a label is supported
  pull_request:
    types:
      - labeled
    branches-ignore:
      - '*docs'
      - '*noci'

jobs:
  Invoker:
    if: github.event.label.name == 'benchmark'
    uses: ./.github/workflows/flows/benchmark.yml
    secrets: inherit
