name: nightly

on:
  schedule:
    - cron: '0 0 * * *'


jobs:
  build:
    uses: ./.github/workflows/flows/default.yml
    secrets: inherit

  multi-architectures:
    uses: ./.github/workflows/invokers/multi-build.yml
    secrets: inherit

  benchmark:
    uses: ./.github/workflows/flows/benchmark.yml
    secrets: inherit
