#include "VecSim/friend_test_decl.h"
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTest_CreateIndexInstance_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTest_addVector_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTest_manageIndexOwnership_Test)
