/*
 *Copyright Redis Ltd. 2021 - present
 *Licensed under your choice of the Redis Source Available License 2.0 (RSALv2) or
 *the Server Side Public License v1 (SSPLv1).
 */

#include "VecSim/friend_test_decl.h"
INDEX_TEST_FRIEND_CLASS(HNSWTest_test_dynamic_hnsw_info_iterator_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTest_preferAdHocOptimization_Test)
INDEX_TEST_FRIEND_CLASS(HNSWMultiTest_test_dynamic_hnsw_info_iterator_Test)
INDEX_TEST_FRIEND_CLASS(HNSWMultiTest_preferAdHocOptimization_Test)
INDEX_TEST_FRIEND_CLASS(HNSWMultiTest_MultiBatchIteratorHeapLogic_Test)
INDEX_TEST_FRIEND_CLASS(IndexAllocatorTest_testIncomingEdgesSet_Test)
INDEX_TEST_FRIEND_CLASS(IndexAllocatorTest_test_hnsw_reclaim_memory_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTest_markDelete_Test)
INDEX_TEST_FRIEND_CLASS(HNSWMultiTest_markDelete_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTest_allMarkedDeletedLevel_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTestParallel)
INDEX_TEST_FRIEND_CLASS(HNSWTestParallel_parallelSearchKnn_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTestParallel_parallelSearchCombined_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTestBasic_deleteFromHNSWMultiLevels_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTest_deleteFromHNSWWithRepairJobExec_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTest_testIncomingEdgesSize_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTest_swapJobBasic_Test)
