/*
 *Copyright Redis Ltd. 2021 - present
 *Licensed under your choice of the Redis Source Available License 2.0 (RSALv2) or
 *the Server Side Public License v1 (SSPLv1).
 */

#include "VecSim/friend_test_decl.h"
INDEX_TEST_FRIEND_CLASS(HNSWMultiTest_empty_index_Test)
INDEX_TEST_FRIEND_CLASS(HNSWMultiTest_search_more_than_there_is_Test)
INDEX_TEST_FRIEND_CLASS(HNSWMultiTest_indexing_same_vector_Test)
INDEX_TEST_FRIEND_CLASS(HNSWMultiTest_test_dynamic_hnsw_info_iterator_Test)
INDEX_TEST_FRIEND_CLASS(HNSWMultiTest_preferAdHocOptimization_Test)
INDEX_TEST_FRIEND_CLASS(HNSWMultiTest_testSizeEstimation_Test)
INDEX_TEST_FRIEND_CLASS(HNSWMultiTest_markDelete_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTest_testSizeEstimation_Test)
INDEX_TEST_FRIEND_CLASS(HNSWMultiTest_removeVectorWithSwaps_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTest_swapJobBasic_Test)
