/*
 * Copyright (c) 2006-Present, Redis Ltd.
 * All rights reserved.
 *
 * Licensed under your choice of the Redis Source Available License 2.0
 * (RSALv2); or (b) the Server Side Public License v1 (SSPLv1); or (c) the
 * GNU Affero General Public License v3 (AGPLv3).
 */
#include "VecSim/friend_test_decl.h"
INDEX_TEST_FRIEND_CLASS(HNSWTest_test_dynamic_hnsw_info_iterator_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTest_preferAdHocOptimization_Test)
INDEX_TEST_FRIEND_CLASS(HNSWMultiTest_test_dynamic_hnsw_info_iterator_Test)
INDEX_TEST_FRIEND_CLASS(HNSWMultiTest_preferAdHocOptimization_Test)
INDEX_TEST_FRIEND_CLASS(HNSWMultiTest_MultiBatchIteratorHeapLogic_Test)
INDEX_TEST_FRIEND_CLASS(IndexAllocatorTest_testIncomingEdgesSet_Test)
INDEX_TEST_FRIEND_CLASS(IndexAllocatorTest_test_hnsw_reclaim_memory_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTest_markDelete_Test)
INDEX_TEST_FRIEND_CLASS(HNSWMultiTest_markDelete_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTest_allMarkedDeletedLevel_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTestParallel)
INDEX_TEST_FRIEND_CLASS(HNSWTestParallel_parallelSearchKnn_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTestParallel_parallelSearchCombined_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTestBasic_deleteFromHNSWMultiLevels_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTest_deleteFromHNSWWithRepairJobExec_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTest_swapJobBasic_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTestBasic_deleteInplaceAvoidUpdatedMarkedDeleted_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTest_relabelVector_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTest_relabelVectorRejects_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTest_relabelVectorMarkedDeleted_Test)
INDEX_TEST_FRIEND_CLASS(HNSWMultiTest_relabelVectorMulti_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTestBasic_relabelVectorFlatOnly_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTestBasic_relabelVectorBothTiers_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTestBasic_relabelVectorMulti_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTestBasic_relabelVectorRejects_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTestBasic_relabelVectorDuringIngestion_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTestBasic_updateVectorsBuffered_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTestBasic_updateVectorsIndexed_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTestBasic_updateVectorsMultiChangesCount_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTestBasic_updateVectorsRejectsSeveralVectorsInSingle_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTestBasic_updateVectorsInPlace_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTest_updateVectors_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTest_updateVectorsRejectsSeveralVectorsInSingle_Test)
INDEX_TEST_FRIEND_CLASS(HNSWMultiTest_updateVectorsMulti_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTestBasic_updateVectorsInTheIngestWindow_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTestBasic_updateVectorsWithFullFlatBuffer_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTestBasic_updateVectorsTwiceBeforeIngestion_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTestBasic_updateVectorsAsync_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTieredIndexTestBasic_addRelabelAndUpdateTogetherUnderLoad_Test)
