#include "VecSim/friend_test_decl.h"
INDEX_TEST_FRIEND_CLASS(HNSWTest_test_dynamic_hnsw_info_iterator_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTest_preferAdHocOptimization_Test)
INDEX_TEST_FRIEND_CLASS(HNSWTest_testSizeEstimation_Test)
INDEX_TEST_FRIEND_CLASS(IndexAllocatorTest_testIncomingEdgesSet_Test)
INDEX_TEST_FRIEND_CLASS(IndexAllocatorTest_test_hnsw_reclaim_memory_Test)
