#!/bin/bash

PROGNAME="${BASH_SOURCE[0]}"
HERE="$(cd "$(dirname "$PROGNAME")" &>/dev/null && pwd)"
READIES=$(cd $HERE/../deps/readies && pwd)
. $READIES/shibumi/defs

CFILE=$(mktemp /tmp/test.XXXXXX.c)

CC=${CC:-gcc}
CC_NAME=${CC_NAME:-GCC}

have_march() {
	local arch=$1
	
	if $CC -march="$arch" -E -c $CFILE &> /dev/null; then
		local HAVE="HAVE_MARCH_${arch//-/_}"
		HAVE=${HAVE^^}
		echo "$HAVE"
	fi
}

HAVE_FLAGS=""
HAVE_FLAGS+=" $(have_march x86-64-v2)"
HAVE_FLAGS+=" $(have_march x86-64-v3)"
HAVE_FLAGS+=" $(have_march x86-64-v4)"

rm -f $CFILE

echo "$HAVE_FLAGS" | xargs
