// Generated by tests/unit/generate_tq_golden_header.py
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace tq_golden_fixture {

inline constexpr std::size_t kMaxDim = 16;
inline constexpr std::size_t kMaxPairs = 8;
inline constexpr std::size_t kMaxProjections = 16;

struct OracleCase {
    const char *name;
    const char *metric;
    std::size_t dim;
    std::size_t bits;
    std::size_t projections;
    std::size_t seed;
    std::array<float, kMaxDim> vector;
    std::array<float, kMaxDim> query;
    std::array<float, kMaxPairs> radii;
    std::array<std::uint16_t, kMaxPairs> angle_indices;
    std::array<std::int8_t, kMaxProjections> residual_signs;
    float inner_product_estimate;
    float l2_distance_estimate;
    float code_norm_sq;
    float exact_inner_product;
    float exact_l2_distance;
};

inline constexpr std::array<OracleCase, 3> kCases = {
    OracleCase{
        "ip_bits8_proj8_seed7",
        "ip",
        16,
        8,
        8,
        7,
        {0.25f, -1.5f, 0.75f, 2.0f, -0.5f, 1.25f, -0.75f, 0.125f, 0.33f, -0.66f, 1.0f, -1.2f, 0.8f,
         -0.4f, 1.5f, -0.9f},
        {-0.3f, 0.7f, -1.1f, 1.3f, 0.9f, -0.2f, 0.4f, -1.5f, 0.6f, 0.1f, -0.8f, 1.1f, -0.7f, 0.5f,
         -1.0f, 0.2f},
        {0.658991f, 1.2977839f, 0.44358364f, 3.115397f, 0.9265447f, 1.4073212f, 0.53801566f,
         0.98012984f},
        {88, 52, 43, 82, 96, 85, 86, 95},
        {-1, -1, 1, 1, 1, 1, 1, -1, 0, 0, 0, 0, 0, 0, 0, 0},
        -7.2185946f,
        41.28732f,
        16.11013f,
        -4.9655004f,
        36.781128f,
    },
    OracleCase{
        "cosine_bits8_proj8_seed7",
        "cosine",
        16,
        8,
        8,
        7,
        {0.062286016f, -0.3737161f, 0.18685804f, 0.49828812f, -0.12457203f, 0.31143007f,
         -0.18685804f, 0.031143008f, 0.082217544f, -0.16443509f, 0.24914406f, -0.29897287f,
         0.19931525f, -0.099657625f, 0.3737161f, -0.22422965f},
        {-0.09154174f, 0.21359739f, -0.33565304f, 0.39668086f, 0.2746252f, -0.061027825f,
         0.12205565f, -0.4577087f, 0.18308347f, 0.030513912f, -0.2441113f, 0.33565304f,
         -0.21359739f, 0.15256956f, -0.30513912f, 0.061027825f},
        {0.16418372f, 0.32333514f, 0.11051621f, 0.7761828f, 0.2308431f, 0.35062572f, 0.13404344f,
         0.2441935f},
        {88, 52, 43, 82, 96, 85, 86, 95},
        {-1, -1, 1, 1, 1, 1, 1, -1, 0, 0, 0, 0, 0, 0, 0, 0},
        -1.0683612f,
        4.1367226f,
        1.0000005f,
        -0.37749517f,
        2.7549906f,
    },
    OracleCase{
        "ip_bits16_proj16_seed11",
        "ip",
        16,
        16,
        16,
        11,
        {1.2f, -0.8f, 0.4f, -1.6f, 0.9f, 0.3f, -0.7f, 1.1f, -1.4f, 0.2f, 0.6f, -0.9f, 1.8f, -1.1f,
         0.5f, 0.75f},
        {-0.5f, 1.4f, -0.2f, 0.8f, -1.0f, 0.65f, 0.45f, -0.35f, 1.25f, -0.55f, 0.95f, -1.3f, 0.15f,
         0.85f, -0.6f, 1.05f},
        {0.5712914f, 2.551377f, 1.1872723f, 0.5565233f, 0.69208604f, 0.9180033f, 2.3449142f,
         0.67597055f},
        {29076, 5213, 32315, 7455, 21615, 25245, 11254, 15422},
        {-1, -1, -1, -1, -1, -1, 1, 1, -1, 1, -1, -1, 1, 1, 1, -1},
        -3.1569238f,
        33.44885f,
        15.832504f,
        -4.7825f,
        36.7f,
    },
};

} // namespace tq_golden_fixture
