name: alpine 3 flow

on: [workflow_dispatch, workflow_call]

jobs:
  alpine3:
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: alpine:3
      pre-checkout-script: apk add bash git
      run-asan: true
