name: amazon linux 2 flow

on: [workflow_dispatch, workflow_call]

jobs:
  amazonlinux2:
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: amazonlinux:2
      pre-checkout-script: yum install -y tar gzip
