name: build

on:
  push:
    branches: [main, '[0-9].[0-9]']
  pull_request:
    branches-ignore: ['*docs', '*noci']


jobs:
  build:
    name: default build job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install dependencies
        run: .install/install_script.sh
      - name: install python packages
        run: pip3 install -r requirements.txt
      - name: check format
        run: make check-format
      - name: unit tests
        run: make unit_test
      - name: flow tests
        run: make flow_test
      - name: valgrind
        run: make valgrind
      - name: Archive valgrind tests reports
        uses: actions/upload-artifact@v3
        with:
          name: valgrind tests reports
          path: bin/Linux-x86_64-debug/unit_tests/Testing/Temporary/
