name: debian trixie flow

on: [workflow_dispatch, workflow_call]

jobs:
  trixie:
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: gcc:14-trixie
      pre-checkout-script: apt-get update && apt-get -y install git
