name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  benchmark:
    uses: ./.github/workflows/benchmark.yml
    secrets: inherit
    with:
      setup: '' # default behavior

  jammy:
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: ubuntu:jammy
      run-valgrind: false
  focal:
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: ubuntu:focal
      run-valgrind: false
#  bionic:
#    uses: ./.github/workflows/task-unit-test.yml
#    with:
#      container: ubuntu:bionic
#      run-valgrind: false
  bullseye:
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: debian:bullseye
      run-valgrind: false
#  amazonlinux2:
#    uses: ./.github/workflows/amazon2.yml
  mariner2:
    uses: ./.github/workflows/mariner2.yml
  rocky8:
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: rockylinux:8
      run-valgrind: false
  rocky9:
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: rockylinux:9
      run-valgrind: false
  alpine3:
    uses: ./.github/workflows/alpine3.yml
  macos:
    uses: ./.github/workflows/macos.yml
  arm:
    uses: ./.github/workflows/arm.yml
    secrets: inherit

  notify-on-failure:
    needs:
      - benchmark
      - jammy
      - focal
#      - bionic
      - bullseye
#      - amazonlinux2
      - mariner2
      - rocky8
      - rocky9
      - alpine3
      - macos
      - arm
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Notify on failure
        uses: slackapi/slack-github-action@v1
        with:
          payload: '{ "failed_run": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_NIGHTLY_FAILURE }}
