name: Merge a Pull-Request Flow

on:
  push:

  merge_group:
    types: [checks_requested]

jobs:
  check-if-docs-only:
    uses: ./.github/workflows/task-check-docs.yml

  jammy:
    needs: [check-if-docs-only]
    if: ${{ needs.check-if-docs-only.outputs.only-docs-changed == 'false' }}
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: ubuntu:jammy
  focal:
    needs: [check-if-docs-only]
    if: ${{ needs.check-if-docs-only.outputs.only-docs-changed == 'false' }}
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: ubuntu:focal
  bionic:
    needs: [check-if-docs-only]
    if: ${{ needs.check-if-docs-only.outputs.only-docs-changed == 'false' }}
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: ubuntu:bionic
  xenial:
    needs: [check-if-docs-only]
    if: ${{ needs.check-if-docs-only.outputs.only-docs-changed == 'false' }}
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: ubuntu:xenial
  bullseye:
    needs: [check-if-docs-only]
    if: ${{ needs.check-if-docs-only.outputs.only-docs-changed == 'false' }}
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: debian:bullseye
  centos7:
    needs: [check-if-docs-only]
    if: ${{ needs.check-if-docs-only.outputs.only-docs-changed == 'false' }}
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: centos:7
  amazonlinux2:
    needs: [check-if-docs-only]
    if: ${{ needs.check-if-docs-only.outputs.only-docs-changed == 'false' }}
    uses: ./.github/workflows/amazon2.yml
  mariner2:
    needs: [check-if-docs-only]
    if: ${{ needs.check-if-docs-only.outputs.only-docs-changed == 'false' }}
    uses: ./.github/workflows/mariner2.yml
  rocky8:
    needs: [check-if-docs-only]
    if: ${{ needs.check-if-docs-only.outputs.only-docs-changed == 'false' }}
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: rockylinux:8
  rocky9:
    needs: [check-if-docs-only]
    if: ${{ needs.check-if-docs-only.outputs.only-docs-changed == 'false' }}
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: rockylinux:9
  macos:
    needs: [check-if-docs-only]
    if: ${{ needs.check-if-docs-only.outputs.only-docs-changed == 'false' }}
    uses: ./.github/workflows/macos.yml
  arm:
    needs: [check-if-docs-only]
    if: ${{ needs.check-if-docs-only.outputs.only-docs-changed == 'false' }}
    uses: ./.github/workflows/arm.yml
    secrets: inherit

  coverage:
    needs: [check-if-docs-only]
    if: ${{ needs.check-if-docs-only.outputs.only-docs-changed == 'false' }}
    uses: ./.github/workflows/coverage.yml
    secrets: inherit

  pr-validation:
    needs:
      - check-if-docs-only
      - jammy
      - focal
      - bionic
      - xenial
      - bullseye
      - centos7
      - amazonlinux2
      - mariner2
      - rocky8
      - rocky9
      - macos
      - arm
      - coverage
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
