name: Merge a Pull-Request Flow
run-name: Validate ${{ github.ref_name }}

on:
  workflow_dispatch:
  workflow_call:
  merge_group:
    types: [checks_requested]

jobs:

  jammy:
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: ubuntu:jammy
  focal:
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: ubuntu:focal
#  bionic:
#    needs: [check-if-docs-only]
#    if: ${{ needs.check-if-docs-only.outputs.only-docs-changed == 'false' }}
#    uses: ./.github/workflows/task-unit-test.yml
#    with:
#      container: ubuntu:bionic
  bullseye:
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: debian:bullseye
#  amazonlinux2:
#    needs: [check-if-docs-only]
#    if: ${{ needs.check-if-docs-only.outputs.only-docs-changed == 'false' }}
#    uses: ./.github/workflows/amazon2.yml
  mariner2:
    uses: ./.github/workflows/mariner2.yml
  rocky8:
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: rockylinux:8
  rocky9:
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: rockylinux:9
  macos:
    uses: ./.github/workflows/macos.yml
  arm:
    uses: ./.github/workflows/arm.yml
    secrets: inherit

  coverage:
    uses: ./.github/workflows/coverage.yml
    secrets: inherit

  pr-validation:
    needs:
      - jammy
      - focal
#      - bionic
      - bullseye
#      - amazonlinux2
      - mariner2
      - rocky8
      - rocky9
      - macos
      - arm
      - coverage
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
