name: Pull Request CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review] # Defaults + ready_for_review

jobs:

  basic-tests:
    name: basic tests
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    steps:
      - name: Check CPU Vendor
        run: cat /proc/cpuinfo | grep "vendor_id" | uniq
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: install dependencies
        run: sudo .install/install_script.sh
      - name: install python packages
        run: pip3 install -r requirements.txt
      - name: check format
        run: make check-format
      - name: unit tests
        run: make unit_test
      - name: flow tests
        run: make flow_test VERBOSE=1

  coverage:
    needs: [basic-tests]
    if: ${{ !github.event.pull_request.draft}}
    uses: ./.github/workflows/coverage.yml
    secrets: inherit

  codeql-analysis:
    if: ${{ !github.event.pull_request.draft}}
    uses: ./.github/workflows/codeql-analysis.yml
    secrets: inherit

  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@v0
        with:
          config_path: .github/spellcheck-settings.yml
          task_name: Markdown

  pr-validation:
    needs:
      - basic-tests
      - coverage
      - codeql-analysis
      - spellcheck
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
