name: Pull Request CI

on:
  pull_request:

jobs:
  check-if-docs-only:
    uses: ./.github/workflows/task-check-docs.yml

  basic-tests:
    name: basic tests
    runs-on: ubuntu-latest
    needs: check-if-docs-only
    if: needs.check-if-docs-only.outputs.only-docs-changed == 'false'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: install dependencies
        run: sudo .install/install_script.sh
      - name: install python packages
        run: pip3 install -r requirements.txt
      - name: check format
        run: make check-format
      - name: unit tests
        run: make unit_test
      - name: flow tests
        run: make flow_test

  coverage:
    needs: [basic-tests, check-if-docs-only]
    if: ${{ !github.event.pull_request.draft && needs.check-if-docs-only.outputs.only-docs-changed == 'false' }}
    uses: ./.github/workflows/coverage.yml
    secrets: inherit

  codeql-analysis:
    needs: [check-if-docs-only]
    if: ${{ !github.event.pull_request.draft && needs.check-if-docs-only.outputs.only-docs-changed == 'false' }}
    uses: ./.github/workflows/codeql-analysis.yml
    secrets: inherit

  pr-validation:
    needs: [basic-tests, coverage]
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
