name: focal flow

on: [workflow_dispatch]

jobs:
  focal:
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: ubuntu:focal
      pre-checkout-script: apt-get update && apt-get install -y git
