name: full default test

on:
  workflow_call:


jobs:
  build:
    name: default build job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: install dependencies
        run: sudo .install/install_script.sh
      - name: install python packages
        run: pip3 install -r requirements.txt
      - name: check format
        run: make check-format
      - name: unit tests
        run: make unit_test
      - name: flow tests
        run: make flow_test
