name: jammy flow

on: [workflow_dispatch, workflow_call]

jobs:
  jammy:
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: ubuntu:jammy
      pre-checkout-script: apt-get update && apt-get install -y git
