name: nightly

on:
  schedule:
    - cron: '0 0 * * *'


jobs:
  build:
    uses: ./.github/workflows/default.yml

  multi-architectures:
    uses: ./.github/workflows/multi-build.yml

  benchmark:
    uses: ./.github/workflows/benchmark.yml
