# https://github.com/marketplace/actions/run-circle-ci-on-label
name: performance

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - assigned

jobs:
  pref-ci:
    if: github.event.label.name == 'performance'
    runs-on: ubuntu-latest
    name: Run performance benchamrks

    steps:
      - uses: actions/checkout@v2
      - name: circle-ci job runner
        id: curl-circle-ci
        uses: Open-Source-Contrib/circle-ci-trigger-action@latest
        with:
          circle_ci_token: ${{ secrets.CIRCLE_CI_SECRET}}
          circle_ci_job: run-benchmarks
          circle_ci_project_url: ${{ github.event.pull_request.head.ref }}
