# https://github.com/marketplace/actions/run-circle-ci-on-label
name: performance

on:
  pull_request:
    types:
      - labeled

jobs:
  pref-ci:
    if: github.event.label.name == 'run-micro-benchmarks'
    runs-on: ubuntu-latest
    name: Run performance benchamrks

    steps:
      - uses: actions/checkout@v2
      - name: circle-ci job runner
        id: curl-circle-ci
        run: |
          curl --request POST \
          --url https://circleci.com/api/v2/project/github/RedisAI/VectorSimilarity/pipeline \
          --header 'Circle-Token: ${{ secrets.CIRCLE_CI_SECRET }}' \
          --header 'content-type: application/json' \
          --data '{"branch": "${{ github.event.pull_request.head.ref }}",
          "parameters": {"run_default_flow":false, "run_benchmark_flow_label":true}}'
