name: rocky8 flow

on: [workflow_dispatch]

jobs:
  rocky8:
    uses: ./.github/workflows/task-unit-test.yml
    with:
      container: rockylinux:8
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
