name: Test an OS

on:
  workflow_call:
    inputs:
      env:
        description: 'Environment to run tests on'
        type: string
        default: 'ubuntu-latest'
      container:
        description: 'Container to run tests on'
        type: string
      pre-checkout-script:
        description: 'Script to run before checkout'
        type: string
      run-valgrind:
        description: 'Run valgrind tests'
        type: boolean
        default: true

jobs:
  test:
    name: Test ${{ inputs.container || inputs.env }}
    runs-on: ${{ inputs.env }}
    container: ${{ inputs.container || null }}
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    steps:
      - name: pre-checkout script
        if: ${{ inputs.pre-checkout-script }}
        run: ${{ inputs.pre-checkout-script }}
      - name: Check for node20 support
        shell: python
        run: |
          import os
          supported = "${{ inputs.container }}" not in ["amazonlinux:2", "ubuntu:bionic"]
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
              print('supported', str(supported).lower(), sep='=', file=f)
          if not supported:
              with open(os.environ['GITHUB_ENV'], 'a') as f:
                  # https://github.com/actions/checkout/issues/1809
                  print("ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION=node16", file=f)
                  print("ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION=node16", file=f)
                  # https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
                  print("ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true", file=f)
      - name: checkout
        uses: actions/checkout@v4
      - name: install dependencies
        run: .install/install_script.sh ${{ !inputs.container && 'sudo' || '' }}
      - name: unit tests
        run: make unit_test
      - name: valgrind
        if: ${{ inputs.run-valgrind }}
        run: make valgrind
      - name: Archive valgrind tests reports
        if: ${{ inputs.run-valgrind }} && failure()
        uses: actions/upload-artifact@v4
        with:
          name: valgrind tests reports
          path: bin/Linux-x86_64-debug/unit_tests/Testing/Temporary/
