name: Test an OS

on:
  workflow_call:
    inputs:
      env:
        description: 'Environment to run tests on'
        type: string
        default: 'ubuntu-latest'
      container:
        description: 'Container to run tests on'
        type: string
      pre-checkout-script:
        description: 'Script to run before checkout'
        type: string
      run-valgrind:
        description: 'Run valgrind tests'
        type: boolean
        default: true

jobs:
  test:
    name: Test ${{ inputs.container && format('{0} (on {1})', inputs.container, inputs.env) || inputs.env }}
    runs-on: ${{ inputs.env }}
    container: ${{ inputs.container || null }}
    defaults:
      run:
        # Use bash as default shell for every OS other than alpine
        shell: ${{ inputs.container && contains(inputs.container, 'alpine') && 'sh -l -eo pipefail {0}' || 'bash -l -eo pipefail {0}' }}
    steps:
      - name: pre-checkout script
        run: ${{ inputs.pre-checkout-script }}
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Print CPU information
        run: |
          echo "=== CPU Information ==="
          if command -v lscpu >/dev/null 2>&1; then
            echo "--- lscpu output ---"
            lscpu
          elif [[ "$RUNNER_OS" == "macOS" ]] || command -v sysctl >/dev/null 2>&1; then
            echo "--- macOS CPU info ---"
            sysctl -n machdep.cpu.brand_string 2>/dev/null || echo "CPU brand: N/A"
            sysctl -n machdep.cpu.core_count 2>/dev/null || echo "Core count: N/A"
            sysctl -n machdep.cpu.thread_count 2>/dev/null || echo "Thread count: N/A"
            sysctl -n machdep.cpu.vendor 2>/dev/null || echo "CPU vendor: N/A"
            sysctl -n machdep.cpu.features 2>/dev/null || echo "CPU features: N/A"
          else
            echo "--- Fallback CPU info ---"
            cat /proc/cpuinfo 2>/dev/null || echo "CPU info not available"
          fi
          echo "Runner OS: $RUNNER_OS"
          echo "Runner Architecture: ${{ runner.arch }}"
          echo "========================"
      - name: install dependencies
        run: .install/install_script.sh ${{ !inputs.container && 'sudo' || '' }}
      - name: Set Artifact Name
        # Artifact names have to be unique, so we base them on the environment.
        # We also remove invalid characters from the name.
        id: artifact-name
        run: | # Invalid characters include: Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?
          NAME="${{ inputs.container && format('{0} (on {1})', inputs.container, inputs.env) || inputs.env }} ${{ runner.arch }}"
          NAME="$(echo $NAME | sed -e 's/[":\/\\<>\|*?]/_/g')" # Replace invalid characters with underscores
          echo "name=$NAME" >> $GITHUB_OUTPUT

      - name: unit tests
        run: make unit_test
      - name: valgrind
        if: ${{ inputs.run-valgrind }}
        run: make SAN=address unit_test
      - name: Archive valgrind tests reports
        if: ${{ inputs.run-valgrind && failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: valgrind tests reports on ${{ steps.artifact-name.outputs.name }}
          path: bin/Linux-x86_64-debug/unit_tests/Testing/Temporary/
